# Generated by Django 3.1.5 on 2021-01-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_internship_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
